version: "3.6"

services:
  mineru:
    image: mineru:v1.2.0
    container_name: mineru
    networks:
      flyshare:
        ipv4_address: 192.19.0.22
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Shanghai
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DOCKER=True
      - CUDA_VISIBLE_DEVICES=1
      - VIRTUAL_VRAM_SIZE=12 # 与其他计算单元共享显卡资源时配置, 计划分配给mineru服务的显存
    ports:
      - 8002:8000
    volumes:
      - /gpu1_data/models/PDF-Extract-Kit-1___0/models:/tmp/models
      - /gpu1_data/models/layoutreader:/tmp/layoutreader
      - /gpu1_data/paddleocr:/root/.paddleocr
      - /home/gpu1/mineru_bak:/work/MinerU
      - /home/gpu1/mineru_bak/magic-pdf.template.json:/root/magic-pdf.json
networks:
  flyshare:
    name: flyshare
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.19.0.0/24