version: "3.6"

services:
  mineru:
    image: registry.cn-beijing.aliyuncs.com/letmystic/mineru:latest
    container_name: mineru
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Shanghai
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DOCKER=True
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - 8000:8000
    volumes:
      - /home/wgl/mineru:/work/MinerU
      - ./magic-pdf.json:/root/magic-pdf.json